### ISSUE TITLE
Entrevista

### ISSUE THREAD

**Issue by Valentiin01** [SistemasTecTlaxiaco/actividad-2-entrevista-entrevista_equipo-german#2]
[ENTREVISTA.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-entrevista-entrevista_equipo-german/files/12541985/ENTREVISTA.pdf)

**Comment by Heidi-19** [comment]
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
